[build-system]
requires = ["setuptools~=84.0.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "synthDriverHost32-runtime-builder"
dynamic = ["version"]
description = "NVDA 32 bit synth driver host"
maintainers = [
	{name = "NV Access", email = "info@nvaccess.org"},
]
requires-python = ">=3.15.0rc2,<3.16"
classifiers = [
	"Development Status :: 5 - Production/Stable",
	"Intended Audience :: End Users/Desktop",
	"License :: OSI Approved :: GNU General Public License v2 or later (GPLv2+)",
	"Operating System :: Microsoft :: Windows",
	"Programming Language :: Python :: 3",
	"Topic :: Accessibility",
]
readme = "readme.md"
license = {file = "copying.txt"}
dependencies = [
	"comtypes==1.4.16",
	"pyserial==3.5",
	"rpyc==6.0.2",
	"pywin32==312",
	"configobj",
]

[project.urls]
Homepage = "https://www.nvaccess.org/"
Repository = "https://github.com/nvaccess/nvda.git"
Issues = "https://github.com/nvaccess/nvda/issues"

[tool.uv]
default-groups = "all"
python-preference = "only-system"
environments = ["sys_platform == 'win32'"]
required-version = ">=0.9"
no-binary-package = ["py2exe"]

[[tool.uv.dependency-metadata]]
name = "py2exe"
version = "0.14.2.0"
requires-python = ">=3.10,<3.16"
requires-dist = ["cachetools", "packaging", "pefile"]

[tool.uv.sources]
py2exe = { git = "https://github.com/py2exe/py2exe", rev = "1be98bd71ac737f73aa146631ab902b2b1cc43f7" }
configobj = { git = "https://github.com/DiffSK/configobj", rev = "9c8a0a80c767bf8a3d6493ed01df6c351bddca42" }

[dependency-groups]
dev = [
	# Package the 32-bit synth driver host from the same validated py2exe source revision as NVDA.
	"py2exe==0.14.2.0",
	"setuptools~=84.0.0",
]

[tool.setuptools.dynamic]
version = {attr = "buildVersionLoader.version_detailed"}
